"use client";

import { useEffect, useState } from "react";
import { CalendarDays, ChevronDown, Clock3, MapPin, MoreHorizontal, Plus, Trash2, UserRound } from "lucide-react";
import clsx from "clsx";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { FOLDER_COLOR_OPTIONS } from "@/lib/folders/colors";
import { slugifyBookingName } from "@/lib/booking/utils";
import type { BookingEditorProps } from "./editor-types";
import type { BookingEditorSection } from "./types";
import { bookingFormWithName, durationLabel, formAvailabilityLabel, matchBookingHost, nextBookingTimeRange, WEEKDAYS } from "./utils";
import { BookingHostAvatar } from "./booking-host-avatar";

export function BookingEditor({ form, open, editingId, username, hosts, canManageHosts, currentUserId, saving, onChange, onClose, onSave, onDelete, onToggleEnabled, onClosed }: BookingEditorProps) {
	const [activeSection, setActiveSection] = useState<BookingEditorSection>(null);
	const [nameEditing, setNameEditing] = useState(false);
	const [moreOpen, setMoreOpen] = useState(false);
	const [hostQuery, setHostQuery] = useState("");
	const [hostError, setHostError] = useState("");
	useEffect(() => { if (open) { setActiveSection(null); setNameEditing(false); setMoreOpen(false); setHostQuery(""); setHostError(""); } }, [editingId, open]);
	const sectionClass = "border-b border-[var(--border)] px-5 py-5";
	const headingClass = "flex w-full items-center justify-between gap-3 text-left text-base font-semibold text-[var(--foreground)]";
	const fieldClass = "h-10 w-full rounded-xl border border-[var(--border)] bg-[var(--card)] px-3 text-sm";
	const toggle = (section: BookingEditorSection) => setActiveSection((current) => current === section ? null : section);

	return <aside aria-label="Event details" aria-hidden={!open} inert={!open} onTransitionEnd={(event) => { if (event.target === event.currentTarget && event.propertyName === "width" && !open) onClosed(); }} className={clsx("relative z-10 h-full shrink-0 overflow-hidden transition-[width] duration-300 ease-in-out motion-reduce:transition-none", open ? "w-full sm:w-[392px]" : "w-0")}>
		<div className={clsx("flex h-full w-[min(392px,100vw)] flex-col overflow-hidden rounded-t-2xl bg-[var(--card)] shadow-2xl shadow-[color-mix(in_oklab,var(--foreground)_8%,transparent)] transition-transform duration-300 ease-in-out motion-reduce:transition-none", open ? "translate-x-0" : "translate-x-full")}>
			<div className="min-h-0 flex-1 overflow-y-auto overscroll-contain scrollbar-gutter-stable">
				<section className={sectionClass}>
					<div className="flex items-center gap-3">
						<button type="button" onClick={() => setActiveSection("event")} aria-label="Edit event color" className="h-6 w-6 shrink-0 rounded-full" style={{ backgroundColor: form.color }} />
						{nameEditing ? <Input autoFocus aria-label="Meeting name" value={form.name} onChange={(event) => onChange(bookingFormWithName(form, event.target.value))} onBlur={() => setNameEditing(false)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === "Escape") setNameEditing(false); }} placeholder="New meeting" maxLength={120} className="min-w-0 flex-1 cursor-text rounded-xl bg-[var(--muted)] text-xl font-semibold" /> : <button type="button" onClick={() => { setActiveSection("event"); setNameEditing(true); }} className={clsx("min-w-0 flex-1 break-words text-left text-xl font-semibold text-[var(--foreground)]", activeSection === "event" ? "cursor-text rounded-xl bg-[var(--muted)] px-2 py-1" : "hover:text-[var(--primary)]")}>{form.name || "New meeting"}</button>}
						<button type="button" onClick={() => toggle("event")} aria-label="Toggle event details" aria-expanded={activeSection === "event"} className="rounded-xl p-1 text-[var(--muted-foreground)] hover:bg-[var(--muted)]"><ChevronDown className={clsx("h-5 w-5 transition-transform", activeSection === "event" && "rotate-180")} /></button>
					</div>
					{activeSection === "event" && <div className="mt-5 space-y-4"><label className="block text-sm font-medium text-[var(--foreground)]">Link slug<Input value={form.slug} onChange={(event) => onChange({ ...form, slug: slugifyBookingName(event.target.value) })} placeholder="new-meeting" maxLength={80} className="mt-2" /><span className="mt-1 block break-all text-xs font-normal text-[var(--muted-foreground)]">/c/{username || "your-name"}/{form.slug || "event-slug"}</span></label><label className="block text-sm font-medium text-[var(--foreground)]">Description<Textarea value={form.description} onChange={(event) => onChange({ ...form, description: event.target.value })} placeholder="Tell guests what this meeting is about" maxLength={2000} rows={4} className="mt-2 resize-y" /></label><fieldset><legend className="text-sm font-medium text-[var(--foreground)]">Color</legend><div className="mt-2 flex flex-wrap gap-2" role="radiogroup" aria-label="Event color">{FOLDER_COLOR_OPTIONS.map((option) => <button key={option.value} type="button" role="radio" aria-label={option.label} aria-checked={form.color === option.value} onClick={() => onChange({ ...form, color: option.value })} className={clsx("flex h-8 w-8 items-center justify-center rounded-full border-2 border-[var(--card)] ring-2", form.color === option.value ? "ring-[var(--primary)]" : "ring-transparent hover:ring-[var(--border)]")} style={{ backgroundColor: option.value }}>{form.color === option.value && <span className="h-2 w-2 rounded-full bg-[var(--card)]" />}</button>)}</div></fieldset></div>}
				</section>
				<section className={sectionClass}><button type="button" onClick={() => toggle("duration")} aria-expanded={activeSection === "duration"} className={headingClass}><span>Duration</span><ChevronDown className={clsx("h-5 w-5 text-[var(--muted-foreground)] transition-transform", activeSection === "duration" && "rotate-180")} /></button>{activeSection === "duration" ? <div className="mt-4"><Select aria-label="Meeting length" value={[15, 30, 45, 60].includes(form.durationMinutes) ? form.durationMinutes : "custom"} onChange={(event) => onChange({ ...form, durationMinutes: event.target.value === "custom" ? 90 : Number(event.target.value) })} className={fieldClass}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={45}>45 minutes</option><option value={60}>1 hour</option><option value="custom">Custom</option></Select>{![15, 30, 45, 60].includes(form.durationMinutes) && <Input aria-label="Custom minutes" type="number" min={5} max={480} step={5} value={form.durationMinutes} onChange={(event) => onChange({ ...form, durationMinutes: Number(event.target.value) })} className="mt-3" />}</div> : <button type="button" onClick={() => toggle("duration")} className="mt-2 flex w-full items-center gap-2 text-left text-sm text-[var(--muted-foreground)]"><Clock3 className="h-4 w-4" />{durationLabel(form.durationMinutes)}</button>}</section>
				<section className={sectionClass}><button type="button" onClick={() => toggle("location")} aria-expanded={activeSection === "location"} className={headingClass}><span>Location</span><ChevronDown className={clsx("h-5 w-5 text-[var(--muted-foreground)] transition-transform", activeSection === "location" && "rotate-180")} /></button>{activeSection === "location" ? <Input aria-label="Location" value={form.location} onChange={(event) => onChange({ ...form, location: event.target.value })} placeholder="Phone call, video link, or address" maxLength={240} className="mt-4" /> : <button type="button" onClick={() => toggle("location")} className="mt-2 flex w-full items-center gap-2 text-left text-sm text-[var(--muted-foreground)]"><MapPin className="h-4 w-4" />{form.location || "No location set"}</button>}</section>
				<section className={sectionClass}><button type="button" onClick={() => toggle("availability")} aria-expanded={activeSection === "availability"} className={headingClass}><span>Availability</span><ChevronDown className={clsx("h-5 w-5 text-[var(--muted-foreground)] transition-transform", activeSection === "availability" && "rotate-180")} /></button>{activeSection === "availability" ? <div className="mt-4 space-y-4"><fieldset aria-label="Available days"><div className="flex flex-wrap gap-1">{WEEKDAYS.map((day) => <button key={day.value} type="button" aria-label={day.label} aria-pressed={form.weekdays.includes(day.value)} onClick={() => onChange({ ...form, weekdays: form.weekdays.includes(day.value) ? form.weekdays.filter((value) => value !== day.value) : [...form.weekdays, day.value].sort() })} className={clsx("rounded-xl px-3 py-1.5 text-xs font-medium", form.weekdays.includes(day.value) ? "bg-[var(--primary)] text-[var(--primary-foreground)]" : "bg-[var(--muted)] text-[var(--muted-foreground)] hover:bg-[color-mix(in_oklab,var(--muted)_80%,var(--foreground))]")}>{day.short}</button>)}</div></fieldset><div className="flex flex-row gap-8 mt-2"><p className="text-sm font-medium text-[var(--foreground)] mt-3">Times</p>

					<div className="space-y-2 flex flex-col items-start flex-1 min-w-0 w-full">{form.timeRanges.map((range, index) => <div key={index} className="flex items-end gap-2 w-full"><label className="min-w-0 flex-1 text-xs text-[var(--muted-foreground)]">From<Input type="time" step={900} value={range.startTime} onChange={(event) => onChange({ ...form, timeRanges: form.timeRanges.map((item, itemIndex) => itemIndex === index ? { ...item, startTime: event.target.value } : item) })} className="mt-1 flex-1 min-w-0" /></label><label className="min-w-0 flex-1 text-xs text-[var(--muted-foreground)]">To<Input type="time" step={900} value={range.endTime} onChange={(event) => onChange({ ...form, timeRanges: form.timeRanges.map((item, itemIndex) => itemIndex === index ? { ...item, endTime: event.target.value } : item) })} className="mt-1 flex-1 min-w-0" /></label><button type="button" aria-label={`Remove time ${index + 1}`} disabled={form.timeRanges.length === 1} onClick={() => onChange({ ...form, timeRanges: form.timeRanges.filter((_, itemIndex) => itemIndex !== index) })} className="mb-1 rounded-xl p-2 text-[var(--muted-foreground)] hover:bg-[var(--muted)] disabled:opacity-30"><Trash2 className="h-4 w-4" /></button></div>)}

						<button type="button" disabled={form.timeRanges.length >= 12} onClick={() => onChange({ ...form, timeRanges: [...form.timeRanges, nextBookingTimeRange(form.timeRanges, form.durationMinutes)] })} className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-[var(--primary)] hover:text-[var(--compose)] disabled:opacity-50"><Plus className="h-4 w-4" />Add time</button>
					</div></div>
					<p className="text-xs text-[var(--muted-foreground)]">Times use {form.timeZone}.</p></div> : <button type="button" onClick={() => toggle("availability")} className="mt-2 flex w-full items-center gap-2 text-left text-sm text-[var(--muted-foreground)]"><CalendarDays className="h-4 w-4 shrink-0" />{formAvailabilityLabel(form)}</button>}</section>
				<section className={sectionClass}>
					<button type="button" onClick={() => toggle("host")} aria-expanded={activeSection === "host"} className={headingClass}><span>Host</span><ChevronDown className={clsx("h-5 w-5 text-[var(--muted-foreground)] transition-transform", activeSection === "host" && "rotate-180")} /></button>
					{activeSection === "host" ? <div className="mt-4 space-y-4">
						<div className="space-y-2">{form.hostIds.map((id) => { const host = hosts.find((item) => item.id === id); const isCurrentUser = id === currentUserId; return <div key={id} className="flex items-center gap-3 rounded-xl bg-[var(--muted)] px-3 py-2">{host ? <BookingHostAvatar host={host} currentUserId={currentUserId} /> : <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--muted)] text-[var(--muted-foreground)]"><UserRound className="h-4 w-4" /></span>}<span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-[var(--foreground)]">{host?.name || "Unavailable user"}{isCurrentUser ? " (you)" : ""}</span><span className="block truncate text-xs text-[var(--muted-foreground)]">{host?.email}</span></span>{!isCurrentUser && <button type="button" onClick={() => onChange({ ...form, hostIds: form.hostIds.filter((hostId) => hostId !== id) })} className="text-xs font-medium text-[var(--muted-foreground)] hover:text-[var(--destructive)]">Remove</button>}</div>; })}</div>
						{canManageHosts && <form onSubmit={(event) => { event.preventDefault(); const match = matchBookingHost(hosts, hostQuery); if (!match.host) { setHostError(match.error); return; } if (form.hostIds.includes(match.host.id)) { setHostError("This user is already a host."); return; } if (form.hostIds.length >= 20) { setHostError("A booking can have up to 20 hosts."); return; } onChange({ ...form, hostIds: [...form.hostIds, match.host.id] }); setHostQuery(""); setHostError(""); }}><label htmlFor="booking-host-input" className="block text-sm font-medium text-[var(--foreground)]">Add a host</label><div className="mt-2 flex gap-2"><Input id="booking-host-input" value={hostQuery} onChange={(event) => { setHostQuery(event.target.value); setHostError(""); }} placeholder="Name or email" autoComplete="off" aria-invalid={!!hostError} aria-describedby={hostError ? "booking-host-error" : undefined} className="min-w-0 flex-1" /><Button type="submit" variant="outline" className="shrink-0 rounded-xl">Add</Button></div>{hostError && <p id="booking-host-error" role="alert" className="mt-2 text-xs text-[var(--destructive)]">{hostError}</p>}</form>}
					</div> : <button type="button" onClick={() => toggle("host")} className="mt-2 flex w-full items-center gap-2 text-left text-sm text-[var(--muted-foreground)]"><span className="flex shrink-0 -space-x-1">{form.hostIds.slice(0, 3).map((id) => { const host = hosts.find((item) => item.id === id); return host ? <BookingHostAvatar key={id} host={host} currentUserId={currentUserId} size="small" /> : <span key={id} className="flex h-5 w-5 items-center justify-center rounded-full bg-[var(--muted)]"><UserRound className="h-3 w-3" /></span>; })}</span><span className="truncate">{form.hostIds.map((id) => hosts.find((host) => host.id === id)?.name ?? "User").join(", ")}</span></button>}
				</section>
			</div>
			<div className="relative flex shrink-0 items-center justify-end gap-2 border-t border-[var(--border)] bg-[var(--card)] px-4 py-3">{editingId && <div className="relative"><Button type="button" variant="outline" onClick={() => setMoreOpen((value) => !value)} className="h-9 rounded-xl px-3"><MoreHorizontal className="h-4 w-4" />More</Button>{moreOpen && <div className="absolute bottom-full right-0 z-20 mb-2 w-40 rounded-xl border border-[var(--border)] bg-[var(--card)] p-1 shadow-lg"><button type="button" onClick={() => { setMoreOpen(false); onToggleEnabled(); }} className="block w-full rounded-xl px-3 py-2 text-left text-sm hover:bg-[var(--muted)]">Turn {form.enabled ? "off" : "on"}</button><button type="button" onClick={() => { setMoreOpen(false); onDelete(); }} className="block w-full rounded-xl px-3 py-2 text-left text-sm text-[var(--destructive)] hover:bg-[color-mix(in_oklab,var(--destructive)_12%,var(--card))]">Delete</button></div>}</div>}<Button type="button" variant="ghost" disabled={saving} onClick={onClose} className="h-9 rounded-xl px-4">Cancel</Button><Button type="button" disabled={saving} onClick={onSave} className="h-9 rounded-xl bg-[var(--primary)] px-4 text-[var(--primary-foreground)] hover:bg-[color-mix(in_oklab,var(--primary)_88%,var(--foreground))]">{saving ? "Saving…" : editingId ? "Save changes" : "Create"}</Button></div>
		</div>
	</aside>;
}
